version: '2'

services:

  rabbitMq:
    image: rabbitmq:3-management
    ports:
      - "15671-15672:15671-15672"
      - "4369:4369"
      - "5671-5672:5671-5672"
      - "25672:25672"

  mysql:
    build:
      context: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bookorders
      - MYSQL_USER=bookorder_service
      - MYSQL_PASSWORD=123

  email:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"